# https://yarnpkg.com/configuration/yarnrc

nodeLinker: node-modules

logFilters:
  - code: YN0004
    level: discard
  - code: YN0013
    level: discard
  - code: YN0019
    level: discard
  - code: YN0076
    level: discard
  - code: YN0086
    level: discard

compressionLevel: mixed
enableGlobalCache: false
enableHardenedMode: true
enableScripts: false
npmMinimalAgeGate: 2d
