# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: 'Docker - Setup Buildx'
description: 'GitHub Action to set up Docker Buildx'
author: 'crazy-max'
branding:
  color: 'blue'
  icon: 'truck'

inputs:
  buildx-version:
    description: 'Buildx version. Example: v0.3.0'
    default: 'latest'
    required: false
  install:
    description: 'Sets up docker build command as an alias to docker buildx'
    default: 'false'
    required: false

outputs:
  platforms:
    description: 'Available platforms (comma separated)'

runs:
  using: 'node12'
  main: 'dist/index.js'
  post: 'dist/index.js'
