# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: 'Docker Setup QEMU'
description: 'Install QEMU static binaries'
author: 'docker'
branding:
  icon: 'anchor'
  color: 'blue'

inputs:
  image:
    description: 'QEMU static binaries Docker image. e.g. tonistiigi/binfmt:latest'
    default: 'tonistiigi/binfmt:latest'
    required: false
  platforms:
    description: 'Platforms to install. e.g. arm64,riscv64,arm'
    default: 'all'
    required: false

outputs:
  platforms:
    description: 'Available platforms (comma separated)'

runs:
  using: 'node12'
  main: 'dist/index.js'
